import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Title from "@/components/Title";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} 
        antialiased h-screen flex flex-col overflow-hidden`}
			>
				<header className="py-4 w-full bg-slate-900">
					<Title text="My Todos" />
				</header>
				{children}
				<footer className="py-2 text-center bg-slate-900 w-full">
					&copy;&nbsp;Crée par Mathieu Tourret
				</footer>
			</body>
		</html>
	);
}
